name: Makefile CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y jq
        wget https://downloads.nestybox.com/sysbox/releases/v0.6.2/sysbox-ce_0.6.2-0.linux_amd64.deb
        sudo apt install -y ./sysbox-ce_0.6.2-0.linux_amd64.deb

    - name: Build builder
      run: make builder

    - name: Build
      run: VERSION=${GITHUB_REF#refs/*/} make disk.img

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/*.img.*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
