name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make disk.img

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
