name: Makefile CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make deps

    - name: Build
      run: VERSION=${GITHUB_REF#refs/*/} make disk.img
      
    - name: Checksum & compress
      run: make disk.img.sha256 part.img.sha256 disk.img.gz part.img.gz

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/*.img.*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
